# #9.3 Testing createAccount part II

## e2e 테스트 도중 계속 발생하는 에러

### 에러 메시지

```
Jest did not exit one second after the test run has completed. This usually
means that there are asynchronous operations that weren't stopped in your tests.
Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

### 확인

```
$ "jest --config ./test/jest-e2e.json --detectOpenHandles"

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at new CacheableLookup (../node_modules/cacheable-lookup/source/index.js:75:14)
      at Object.<anonymous> (../node_modules/got/dist/source/core/index.js:32:24)
      at Object.<anonymous> (../node_modules/got/dist/source/as-promise/types.js:14:16)
```

- `got` 모듈 : account를 생성할 때마다 이메일을 전송한다.

### 해결

```ts
jest.mock('got', () => {
  return {
    post: jest.fn(),
  };
});
```

- `got`을 mocking한다.

## createAccount() - should fail if account already exists

### 코드

```ts
it('should fail if account already exists', () => {
  return request(app.getHttpServer())
    .post(GRAPHQL_ENDPOINT)
    .send({
      query: `
            mutation {
              createAccount(input: {
                email: "${EMAIL}",
                password: "12345",
                role: Owner
              }) {
                ok
                error
              }
            }
          `,
    })
    .expect(200)
    .expect(res => {
      expect(res.body.data.createAccount.ok).toBe(false);
      expect(res.body.data.createAccount.error).toEqual(expect.any(String));
    });
});
```

- 이전 `should create account`테스트에서 생성된 계정과 같은 이메일로 테스트를 진행하면 올바르게 에러 메시지가 출력되는지 확인한다.
- `toBe()`와는 다르게 `toEqual()`은 완전 일치하지 않아도 테스트에 성공한다.
